---

- hosts: localhost
  gather_facts: false
  become: true

  tasks:


  - name: copy kubeconfig
    fetch: 
      src: /root/.kube/config
      dest: ../kubeconfig
      flat: yes      
    delegate_to: "{{groups['masters'] | first}}"

  - name: label new nodes with project label
    shell: oc --config=../kubeconfig label node {{item}} project={{projectName}}
    with_items:
      - "{{groups['new_nodes']}}"
    ignore_errors: yes

  - name: prepare repo clone dir
    file:
      path: clonedrepo/
      state: directory

  - name: update remote inventory ini file | clone repo
    git: 
      repo: '{{gitlabUrl}}/{{repoName}}.git'
      dest: clonedrepo/
      clone: yes
      update: yes
      force: yes

  - name: run git config for awx
    shell: "git config --global user.email example@example.com && git config --global user.name example"

  - name: update remote inventory ini file | change new_nodes to nodes
    replace:
      path: "clonedrepo/inventories/{{dynamicinvfile}}"
      regexp: 'new_nodes'
      replace: nodes

  - name: perform ssh copy id to all nodes
    shell: |
      set prompt "#|>|\\\$"
      spawn cd clonedrepo/ && git add . && git commit -m "." && git push origin master
      expect {"Username" { send "rockocoop\r";exp_continue} "Password"}
      send "rockocoop\r"
      expect {"password:" { send "Bi11yJ3an!\r";exp_continue} "Bi11yJ3an!"}
      send "Bi11yJ3an!\r"
      expect -re $prompt
    args:
      executable: /usr/bin/expect

#  - name: update remote inventory ini file | commit and push to repo
#    shell:  'cd clonedrepo/ && git add . && git commit -m "." && git push origin master'
